### PR TITLE
feat: improve UX when `closeOnSelect` option is off

### PR DESCRIPTION
**Pull request by ZuBB**
With this change we bring few micropatches to improve UX for all
subparts of select2 component when {closeOnSelect: false} option is
passed to its config

https://projects.mbww.com/browse/AR-4014

### CODE REVIEW

**Comment by ZuBB** [comment]
⚠️  when you will do review please ignore 🔍  changes from any file in `dist/` folder those ar brought automatically by build system and appeared due to non strict version match of deps

screen shot 2017-04-12 at 21 57 58

**Comment by ZuBB** [comment]
files in `dist` dir has been rebuilt to reduce diff size of MR

actual amount changes you can see in next pict

screen shot 2017-04-13 at 12 43 31

**Comment by ZuBB** [comment]
everything is ready feel free to start your reviews

**Comment by asubota** [comment]
let's have custom `cadreon` branch instead of `release/4.0.3` ?

**Comment by ZuBB** [comment]
I do not see any profit in that (this repo already is under Cadreon account)

thing that may be improved here is rename this branch to smth like `4.0.3-p1` or add to final commit tag with that name (`4.0.3-p1`)

**Pull request merged**
